prop_mang/urls.py
from django.urls import path

from prop_mang import views

app_name = 'prop_mang'

urlpatterns = [
  
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('apartment/', views.apartment, name='apartment'),
    path('apartment_details/', views.apartment_details, name='apartment_details'),
    path('single/', views.single, name='single'),
    path('news/', views.news, name='news')
]

property_managment/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from prop_mang import views

urlpatterns = [
    path('', views.home, name='home'),
    path("admin/", admin.site.urls),
    path('', include('prop_mang.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prop_mang/models.py
from django.db import models

# Create your models here.

prop_mang/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'prop_mang/index.html')

def about(request):
    return render(request, 'prop_mang/about.html')

def contact(request):
    return render (request, 'prop_mang/contact.html')

def apartment(request):
    return render(request, 'prop_mang/apartments.html')

def apartment_details (request):
    return render(request, 'apartment-detail.html')

def single(request):
    return render(request, 'single.html')

def news(request):
    return render(request, 'prop_mang/news.html')

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  About Us
{% endblock %}

{% block content %}
  
    
  <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('{% static 'prop_mang/images/hero_bg_1.jpg' %}');"
    data-aos="fade" data-stellar-background-ratio="0.5" data-aos="fade">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-7 text-center" data-aos="fade-up" data-aos-delay="400">
          <h1 class="text-white">About Us</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <img src="{% static 'images/img_1.jpg' %}" alt="Image" class="img-fluid">
        </div>
        <div class="col-lg-6">
          <div class="site-section-heading text-center mb-5 w-border col-md-6 mx-auto">
          <h2 class="mb-5">Our Office</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, fugit nam obcaecati fuga itaque deserunt
            officia, error reiciendis ab quod?</p>
        </div>
        </div>
      </div>
    </div>
  </div>

    
    <div class="site-section">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="site-section-heading text-center mb-5 w-border col-md-6 mx-auto">
          <h2 class="mb-5">Team</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, fugit nam obcaecati fuga itaque deserunt
            officia, error reiciendis ab quod?</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_1.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Megan Smith</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_2.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Brooke Cagle</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_3.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Philip Martin</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_4.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Steven Ericson</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_1.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Nathan Dumlao</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5 mb-lg-5">
          <div class="team-member">
  
            <img src="images/person_2.jpg" alt="Image" class="img-fluid">
  
            <div class="text">
  
              <h2 class="mb-2 font-weight-light h4">Brooke Cagle</h2>
              <span class="d-block mb-2 text-white-opacity-05">Co Founder</span>
              <p class="mb-4">Lorem ipsum dolor sit amet consectetur adipisicing elit ullam reprehenderit nemo.</p>
              <p>
                <a href="#" class="text-white p-2"><span class="icon-facebook"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-twitter"></span></a>
                <a href="#" class="text-white p-2"><span class="icon-linkedin"></span></a>
              </p>
            </div>
  
          </div>
        </div>
  
  
      </div>
    </div>
  </div>

    

    
    <div class="site-section">

      <div class="container">

        <div class="row">
          <div class="site-section-heading text-center mb-5 w-border col-md-6 mx-auto" data-aos="fade-up">
            <h2 class="mb-5">Featured Apartments</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, fugit nam obcaecati fuga itaque deserunt officia, error reiciendis ab quod?</p>
          </div>
        </div>
        
        <div class="site-block-retro d-block d-md-flex">

          <a href="#" class="col1 unit-9 no-height" data-aos="fade-up" data-aos-delay="100">
            <div class="image" style="background-image: url('images/img_2.jpg');"></div>
            <div class="unit-9-content">
              <h2>Baltimore Apartment</h2>
              <span>$600/night</span>
            </div>
          </a>

          <div class="col2 ml-auto">

            <a href="#" class="col2-row1 unit-9 no-height" data-aos="fade-up" data-aos-delay="200">
              <div class="image" style="background-image: url('images/img_3.jpg');"></div>
              <div class="unit-9-content">
                <h2>Austin Apartment</h2>
                <span>$290/night</span>
              </div>
            </a>

            <a href="#" class="col2-row2 unit-9 no-height" data-aos="fade-up" data-aos-delay="300">
              <div class="image" style="background-image: url('images/img_1.jpg');"></div>
              <div class="unit-9-content">
                <h2>Atlanta Apartment</h2>
                <span>$1,290/night</span>
              </div>
            </a>

          </div>

        </div>
        
      </div>
    </div>

    
    <div class="site-section block-13 bg-light">
      <div class="container" data-aos="fade-up">
        <div class="row">
          <div class="site-section-heading text-center mb-5 w-border col-md-6 mx-auto">
            <h2 class="mb-5">Love By Our Customers</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, fugit nam obcaecati fuga itaque deserunt officia, error reiciendis ab quod?</p>
          </div>
        </div>
        <div class="nonloop-block-13 owl-carousel">
          
          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_1.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Megan Smith</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_2.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Brooke Cagle</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_3.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Philip Martin</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_1.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Steven Ericson</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_2.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Nathan Dumlao</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

          <div class="text-center p-3 p-md-5 bg-white">
            <div class="mb-4">            
              <img src="images/person_4.jpg" alt="Image" class="w-50 mx-auto img-fluid rounded-circle">
            </div>
            <div class="text-black">
              <h3 class="font-weight-light h5">Brook Smith</h3>
              <p class="font-italic">&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et, iusto. Aliquam illo, cum sed ea? Ducimus quos, ea?&rdquo;</p>
            </div>
          </div>

        </div>
      </div>
    </div>  
    

    
    
    <div class="bg-primary" data-aos="fade">
      <div class="container">
        <div class="row">
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-facebook text-white"></span></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-twitter text-white"></span></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-instagram text-white"></span></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-linkedin text-white"></span></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-pinterest text-white"></span></a>
          <a href="#" class="col-2 text-center py-4 social-icon d-block"><span class="icon-youtube text-white"></span></a>
        </div>
      </div>
    </div>

{% endblock %}

templates/prop_mang/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,700,900|Oswald:400,700"> 
    <link rel="stylesheet" href="{% static 'prop_mang/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static  'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/mediaelementplayer.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/animate.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/fl-bigmug-line.css' %}">
  
    <link rel="stylesheet" href="{% static  'prop_mang/css/aos.css' %}">
    <link rel="stylesheet" href="{% static  'prop_mang/css/style.css' %}">
    
  </head>
  <body>
  
  <div class="site-wrap">

    <div class="site-navbar mt-4">
        <div class="container py-1">
          <div class="row align-items-center">
            <div class="col-8 col-md-8 col-lg-4">
              <a href="#" class="navbar-brand">
                <img src="{% static  'prop_mang/images/five_wells_logo-removebg-preview.png' %}" alt="Logo" class="image-container  img-fluid flex-column" height="150" width="140">
               
              </a>

            </div>
            <div class="col-4 col-md-4 col-lg-8">
              <nav class="site-navigation text-right text-md-right" role="navigation">

                <div class="d-inline-block d-lg-none ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a></div>

                <ul class="site-menu js-clone-nav d-none d-lg-block">
                  <li class="active">
                    <a href="{% url 'home' %}">Home</a>
                  </li>
                  <li><a href="{% url 'prop_mang:about' %}">About</a></li>
                  <li class="has-children">
                    <a href="{% url 'prop_mang:apartment' %}">Apartments</a>
                    <ul class="dropdown arrow-top">
                      <li><a href="#">Apartments</a></li>
                      <li><a href="#">Rooms</a></li>
                      <li><a href="#">Suites</a></li>
                      <li class="has-children">
                        <a href="#">Sub Menu</a>
                        <ul class="dropdown">
                          <li><a href="#">Menu One</a></li>
                          <li><a href="#">Menu Two</a></li>
                          <li><a href="#">Menu Three</a></li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                  <li><a href="{% url 'prop_mang:news' %}">News</a></li>
                  <li><a href="{% url 'prop_mang:contact' %}">Contact</a></li>
                </ul>
              </nav>
            </div>
           

          </div>
        </div>
      </div>
    </div>

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    {% block content %}

    {% endblock %}

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-4">
            <div class="mb-5">
              <h3 class="footer-heading mb-4">About Five Wells</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe pariatur reprehenderit vero atque, consequatur id ratione, et non dignissimos culpa? Ut veritatis, quos illum totam quis blanditiis, minima minus odio!</p>
            </div>
            <div class="mb-5">
              <h3 class="footer-heading mb-4">Subscribe</h3>
              <form action="#" method="post" class="site-block-subscribe">
                <div class="input-group mb-3">
                  <input type="text" class="form-control border-secondary bg-transparent" placeholder="Enter your email"
                    aria-label="Enter Email" aria-describedby="button-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary rounded-top-right-0" type="button" id="button-addon2">Subscribe</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="row mb-5">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Navigations</h3>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Apartments</a></li>
                  <li><a href="#">News</a></li>
                  <li><a href="#">Featured Apartment</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-6">
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Contact Us</a></li>
                  <li><a href="#">Membership</a></li>
                </ul>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <h3 class="footer-heading mb-4">Follow Us</h3>

                <div>
                  <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                  <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
                </div>
              </div>
            </div>

          </div>

          <div class="col-lg-4 mb-5 mb-lg-0">
            <div class="mb-5">
              <h3 class="footer-heading mb-4">Watch Live Streaming</h3>

              <div class="block-16">
                <figure>
                  <img src="images/img_1.jpg" alt="Image placeholder" class="img-fluid rounded">
                  <a href="https://vimeo.com/channels/staffpicks/93951774" class="play-button popup-vimeo"><span class="icon-play"></span></a>
                </figure>
              </div>

            </div>

            

          </div>
          
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
          </div>
          
        </div>
      </div>
    </footer>

  </div>

  <script src="{% static  'prop_mang/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/jquery-migrate-3.0.1.min.js%' %}"></script>
  <script src="{% static  'prop_mang/js/jquery-ui.js' %}"></script>
  <script src="{% static  'prop_mang/js/popper.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/bootstrap.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/owl.carousel.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/mediaelement-and-player.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static  'prop_mang/js/aos.js' %}"></script>
  <script src="{% static  'prop_mang/js/circleaudioplayer.js' %}"></script>

  <script src="{% static  'prop_mang/js/main.js' %}"></script>
    
  </body>
</html>

templates/prop_mang/news.html
{% extends 'prop_mang/base.html' %}
{% load static %}
<!DOCTYPE html>
{% block title %}
News
{% endblock %}

{% block content %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('{% static  'prop_mang/images/hero_bg_1.jpg' %}');"
    data-aos="fade" data-stellar-background-ratio="0.5" data-aos="fade">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-7 text-center" data-aos="fade-up" data-aos-delay="400">
          <h1 class="text-white">News &amp; Events</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
        </div>
      </div>
    </div>
  </div>

  
    
    <div class="site-section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="100">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_4.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="200">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_2.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="300">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_3.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
  
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="100">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_2.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="200">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_3.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
        <div class="col-md-6 col-lg-4 mb-5" data-aos="fade-up" data-aos-delay="300">
          <a href="single.html"><img src="{% static  'prop_mang/images/img_4.jpg' %}" alt="Image" class="img-fluid"></a>
          <div class="p-4 bg-white">
            <span class="d-block text-secondary small text-uppercase">Jan 20th, 2019</span>
            <h2 class="h5 text-black mb-3"><a href="single.html">This Is The Day, Party, Party!</a></h2>
          </div>
        </div>
  
      </div>
  
    </div>
  
    <div class="container mt-5" data-aos="fade-up">
      <div class="row">
        <div class="col-md-12 text-center">
          <div class="site-block-27">
            <ul>
              <li><a href="#">&lt;</a></li>
              <li class="active"><span>1</span></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#">&gt;</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  </div>
{% endblock %}